-- =============================================================
-- Dra. Mew Store — Migración: autogenerar products.id
-- Ejecuta en el SQL Editor de Supabase DESPUÉS de
-- migration_stock_inventario.sql
-- =============================================================

-- products.id era un INTEGER PRIMARY KEY sin secuencia — cada
-- producto nuevo exigía que el admin tecleara un id a mano.
-- Se agrega una identity que arranca justo después del id más
-- alto que exista hoy (incluye ids manuales como -8 o 0; no los
-- toca, solo evita colisiones a futuro). BY DEFAULT (no ALWAYS)
-- para seguir permitiendo un id explícito si alguna vez hace falta.
DO $$
DECLARE
  next_id INTEGER;
BEGIN
  SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM products;
  EXECUTE format(
    'ALTER TABLE products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
    next_id
  );
END $$;
